### ISSUE TITLE
Generate a 32 bit version too?

### ISSUE THREAD

**Issue by flatsiedatsie** [home-assistant-libs/chip-wheels#1]
It would rock if you could also provide a 32 bit version of the necessary wheel.

**Comment by marcelveldt** [comment]
Sorry but that is not possible, only 64 bit architectures are supported.

**Comment by agners** [comment]
Yeah this is essentially a limitation of the Pigweed build system used by the Matter SDK: The Python libs are built using the toolchain for the host architecture. Officially only x86-64 is supported (according [to their FAQs](https://pigweed.dev/docs/faq.html)), but aarch64 seems to work. I've not gotten 32-bit Arm working. At this point, we don't have plans to invest time for it.

**Comment by spudwebb** [comment]
I would be interested in a 32-bit Arm version of the wheels too.
@agners , @marcelveldt , correct me if I'm wrong as I don't have much experience with this kind of stuff, but isn't it possible to build a docker image for 32-bit arm using cross compilation?  https://github.com/project-chip/connectedhomeip/tree/master/integrations/docker/images/chip-build-crosscompile

and how did you build the  docker image for aarch64 ?

**Comment by marcelveldt** [comment]
first of all, not nice to randomly start pinging people ;-)
second, it's 2023. 64 bits is the common standard

Also the SDK itself only supports 64 bits as already mentioned above.

So, time to upgrade to 64 bits ;-)
