### ISSUE TITLE
A question about SSL version

### ISSUE THREAD

**Issue by hidaris** [home-assistant-libs/chip-wheels#16]
Hello, I encountered an error while trying to use this wheel. The error message reads "OSError: /lib/x86_64-linux-gnu/libcrypto.so.1.1: version `OPENSSL_1_1_1' not found (required by /home/dev/python-matter-server/venv/lib/python3.10/site-packages/chip/_ChipDeviceCtrl.so)". However, based on the build action used, it should not depend on OpenSSL 1.1.1 theoretically since Ubuntu 22.04 was used for the build process. It is worth noting that I did not encounter such a problem when building matter SDK on my local machine with Ubuntu 22.04 installed.

**Comment by agners** [comment]
The actual build use containers, see https://github.com/home-assistant-libs/chip-wheels/blob/main/.github/workflows/build.yaml#L83-L88. Those containers are based on Ubuntu 20.04, it seems, so that is why the dependency is on OpenSSL 1.1.1.

For Home Assistant we run on Debian bullseye, which works fine so far, so I didn't really care what it links against...

**Comment by hidaris** [comment]
> 



> The actual build use containers, see https://github.com/home-assistant-libs/chip-wheels/blob/main/.github/workflows/build.yaml#L83-L88. Those containers are based on Ubuntu 20.04, it seems, so that is why the dependency is on OpenSSL 1.1.1.
> 
> For Home Assistant we run on Debian bullseye, which works fine so far, so I didn't really care what it links against...

Understood. So, if I need to debug the Matter server locally, it would be best to use Docker, as indicated in this link: https://github.com/home-assistant-libs/python-matter-server#dockerfile?

**Comment by agners** [comment]
> Understood. So, if I need to debug the Matter server locally, it would be best to use Docker, as indicated in this link: https://github.com/home-assistant-libs/python-matter-server#dockerfile?

When you run Linux, for development I'd just run it natively. You already said you did compile the SDK? Just install the wheels on your build system, either in a venv (and use that for development too) or your regular env.

**Comment by hidaris** [comment]
> > Understood. So, if I need to debug the Matter server locally, it would be best to use Docker, as indicated in this link: https://github.com/home-assistant-libs/python-matter-server#dockerfile?
> 
> When you run Linux, for development I'd just run it natively. You already said you did compile the SDK? Just install the wheels on your build system, either in a venv (and use that for development too) or your regular env.

Yes, but that was for matter1.0. For version 1.1, my original plan was to use the pre-built version directly, but I will manually compile it next.
