### ISSUE TITLE
No aarch64-linux wheels on PyPi since 2023.10.0

### ISSUE THREAD

**Issue by mweinelt** [home-assistant-libs/chip-wheels#23]
Hi, thanks for maintaining these wheels.

I noticed that there are no wheels for aarch64-linux up on PyPi anymore since 2023.10.0.

The CI action seems to have failed because there were no runners available.

### 2023.10.1
![image](https://github.com/home-assistant-libs/chip-wheels/assets/131599/9ae1ad5b-40a6-4c3f-a966-275afcc4ab1b)

### 2023.10.0
![image](https://github.com/home-assistant-libs/chip-wheels/assets/131599/d4bf5e5a-3fa1-4696-b298-285ab036fa58)

This will cause issues when home-assistant 2023.11.0 requires the updated versions on wednesday via `python-matter-server==4.0.0`.

**Comment by marcelveldt** [comment]
Thanks for the report, good catch!
We're looking into this.

**Comment by agners** [comment]
Sorry, there was a problem with the GitHub Action runner. The 2023.10.1 wheels should be available on PyPI now.

**Comment by mweinelt** [comment]
<del>Looks like the arm64 runner is unavailable again.</del> Nevermind, it is busy with another build.

```
Requested labels: ARM64
Job defined at: home-assistant-libs/chip-wheels/.github/workflows/build.yaml@refs/tags/2024.2.1
Waiting for a runner to pick up this job...
```
