### ISSUE TITLE
Repo name change to matter

### ISSUE THREAD

**Issue by guyluz11** [home-assistant-libs/chip-wheels#3]
This repo name should change to matter-wheels as project chip name got changed to matter

**Comment by agners** [comment]
The upstream repository is still named `connectedhomeip`, see https://github.com/project-chip/connectedhomeip.

Also the wheels produced by the upstream repo are named `chip...`. I prefer to follow naming of the upstream repo, but I am fine renaming as soon as upstream changes naming.
